ignore:
  - "src/main/java/org/albacete/simd/experiments" # ignore experiments folder
  - "src/main/java/org/albacete/simd/algorithms/pHCS" # ignore new algorithm (hot-fix)
  - "src/main/java/org/albacete/simd/algorithms/framework" # ignore new ideas (hot-fix)